---
#
# Ansible managed
#
repository:
  description: Install Brightbox ruby packages on your systems.
  homepage: https://buluma.github.io/
  topics: development, ansible, molecule, tox, playbook, hacktoberfest
